version: '3'

volumes: 
  mongo_vol:

networks:
  mongo_net:
    driver: bridge

services:
  mongodb: 
    image: mongo:4.4.3
    ports:
      - 27017:27017
    networks:
      - mongo_net
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

  mongoexpress:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    networks:
      - mongo_net
    links:
      - mongodb
    environment:
      #ME_CONFIG_BASIC_USERNAME: mongouser
      #ME_CONFIG_BASIC_PASSWORD: mongopwd
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongouser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
    
